name: CLI REGRESSION DEBUG $(Date:yyyyMMdd)$(Rev:.r)

resources:
- repo: self

trigger:
  branches:
    exclude:
    - '*'

variables:
- template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/variables.yml

jobs:
- job: Debug
  displayName: Debug
  strategy:
    maxParallel: 3
    matrix:
      instance1:
        Instance_idx: 1
      instance2:
        Instance_idx: 2
  pool:
    name: ${{ variables.ubuntu_pool }}
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        displayName: "Use Python 3.10"
    - bash: |
          set -ev
          pwd
          cli_repo_path=$(pwd)
          echo $cli_repo_path
          echo "##vso[task.setvariable variable=cli_repo_path]$cli_repo_path"

          git clone https://github.com/Azure/azure-cli-extensions.git
          cli_extension_repo_path=$(pwd)/azure-cli-extensions
          echo $cli_extension_repo_path
          echo "##vso[task.setvariable variable=cli_extension_repo_path]$cli_extension_repo_path"
      displayName: 'checkout cli and extension repo'
    - bash: |
        set -ev
        # source env/bin/activate

        python scripts/regression_test/debug_script.py "2" "$(Instance_idx)"
    - template: ../../.azure-pipelines/templates/azdev_setup.yml
      parameters:
        CLIRepoPath: '$(cli_repo_path)'
        CLIExtensionRepoPath: '$(cli_extension_repo_path)'
    - bash: |
        publishResults='false'
        if [[ -f '/$(HOME)/.azdev/env_config/mnt/vss/_work/1/s/env/test_results_$(Instance_idx).txt' ]]; then
          publishResults='true'
        fi
        echo "##vso[task.setvariable variable=publishResults]$publishResults"

    - task: PublishBuildArtifacts@1
      condition: and(succeededOrFailed(), eq(variables.publishResults, 'true'))
      inputs:
        PathtoPublish: '/$(HOME)/.azdev/env_config/mnt/vss/_work/1/s/env/test_results_$(Instance_idx).txt'
        ArtifactName: 'test_results'
        publishLocation: 'Container'

- job: Summarize
  displayName: Summarize
  # dependsOn: Debug
  pool:
    name: ${{ variables.ubuntu_pool }}
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        displayName: "Use Python 3.10"
    - template: ../../.azure-pipelines/templates/azdev_setup.yml
    # - task: DownloadPipelineArtifact@2
    #   displayName: 'Download Pipeline Artifact'
    - task: AzureCLI@1
      displayName: 'Result Summary'
      inputs:
        azureSubscription: 'Azure CLI release'
        scriptLocation: inlineScript
        inlineScript: |
          set -ev
          
          ls $HOME/.azdev -al
          ls ~/.azdev/env_config$BUILD_SOURCESDIRECTORY/env -al

          # # git config
          # git clone https://github.com/Azure/azure-cli-extensions.git
          # cd azure-cli-extensions

          # # git config
          # GITHUB_TOKEN=$(az keyvault secret show --vault-name kv-azuresdk --name azclibot-pat --query value -otsv)
          # git config --global user.email "AzPyCLI@microsoft.com"
          # git config --global user.name "Azure CLI Team"
          # git remote add azclibot https://azclibot:${GITHUB_TOKEN}@github.com/azclibot/azure-cli-extensions.git

          # git fetch azclibot
          # REGRESSION_BRANCHES=$(curl -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/azclibot/azure-cli-extensions/git/matching-refs/heads/regression_test_23193_ | jq '.[] | .ref')
          # echo ${REGRESSION_BRANCHES}

          # for branch in ${REGRESSION_BRANCHES[@]}
          # do
          #   branch=${branch##*/}
          #   branch=${branch%\"*}
          #   echo ${branch}
          #   module=${branch##*_}

          #   pr_title="Extension Regression Test for ${module}"
          #   pr_body="Triggered by CLI Extension Regression Test Pipeline - ADO_BUILD_ID=23193\n\nThere may still exist some failed tests and failed modules, see [details](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=23193&view=artifacts&type=publishedArtifacts) in ADO pipeline"
          #   pr_head="azclibot:${branch}"

          #   curl \
          #   -H "Authorization: token ${GITHUB_TOKEN}" \
          #   -d "{\"title\": \"${pr_title}\", \"body\": \"${pr_body}\", \"head\": \"${pr_head}\", \"base\": \"main\"}" \
          #   https://api.github.com/repos/Azure/azure-cli-extensions/pulls

          #   sleep 5
          # done
