name: YISHI TEST $(Date:yyyyMMdd)$(Rev:.r)

resources:
- repo: self

trigger:
  branches:
    exclude:
    - '*'

variables:
- template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/variables.yml

jobs:
- job: YishiTest
  pool:
    name: ${{ variables.ubuntu_pool }}
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        displayName: "Use Python 3.10"
    - task: AzureCLI@2
      displayName: 'Checkout CLI version and upgrade'
      inputs:
        azureSubscription: $(AZURE_SDK_INFRA_SUB_CONNECTED_SERVICE)
        scriptType: 'bash'
        scriptLocation: inlineScript
        inlineScript: |
          set -ev
          az --version
          az upgrade --yes
          az --version
