name: Generate CLI $(CLI_VERSION) & Extensions' command table $(Date:yyyyMMdd)$(Rev:.r)

resources:
- repo: self

trigger:
  branches:
    exclude:
    - '*'

variables:
- template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/variables.yml

jobs:
- job: GenerateCommandTable
  displayName: Generate Command Table
  pool:
    name: ${{ variables.ubuntu_pool }}
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        displayName: "Use Python 3.10"
    - task: AzureCLI@1
      displayName: 'checkout branch'
      inputs:
        azureSubscription: 'Azure CLI release'
        scriptLocation: inlineScript
        inlineScript: |
          set -ev
          pwd
          if [[ -n "$(CLI_VERSION)" ]]; then
            git remote add upstream https://github.com/Azure/azure-cli.git
            git fetch upstream
            git checkout tags/azure-cli-$(CLI_VERSION) -b azure-cli-$(CLI_VERSION)
          fi

          git clone https://github.com/Azure/azure-cli-extensions.git
          cd azure-cli-extensions
          if [[ -n "$(EXTENSION_COMMIT)" ]]; then
            git checkout $(EXTENSION_COMMIT)
          fi
    - bash: |
        set -ev
        
        python -m venv env
        chmod +x env/bin/activate
        . env/bin/activate
        python -m pip install -U pip
        pip install azdev
        azdev setup -c -r ./azure-cli-extensions --debug

        azdev extension add "*"
        azdev setup -c -r ./azure-cli-extensions --debug

        azdev statistics list-command-table > /tmp/command_table_$(CLI_VERSION).json
      displayName: 'install extensions & list command table'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '/tmp/command_table_$(CLI_VERSION).json'
        ArtifactName: 'command_table_$(CLI_VERSION).json'
        publishLocation: 'Container'