# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


class AcquireToken(AAZCommand):
    """Acquire a policy token in the given subscription for the given request body.
    """

    _aaz_info = {
        "version": "2025-03-01",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/providers/microsoft.authorization/acquirepolicytoken", "2025-03-01"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        # define Arg Group "Operation"

        _args_schema = cls._args_schema
        _args_schema.content = AAZDictArg(
            options=["--content"],
            arg_group="Operation",
            help="The payload of the resource operation.",
        )
        _args_schema.http_method = AAZStrArg(
            options=["--http-method"],
            arg_group="Operation",
            help="The http method of the resource operation.",
        )
        _args_schema.uri = AAZStrArg(
            options=["--uri"],
            arg_group="Operation",
            help="The request URI of the resource operation.",
        )

        content = cls._args_schema.content
        content.Element = AAZAnyTypeArg()

        # define Arg Group "Parameters"

        _args_schema = cls._args_schema
        _args_schema.change_reference = AAZStrArg(
            options=["--change-reference"],
            arg_group="Parameters",
            help="The change reference.",
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        yield self.PolicyTokensAcquire(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class PolicyTokensAcquire(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/acquirePolicyToken",
                **self.url_parameters
            )

        @property
        def method(self):
            return "POST"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-03-01",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                typ=AAZObjectType,
                typ_kwargs={"flags": {"required": True, "client_flatten": True}}
            )
            _builder.set_prop("changeReference", AAZStrType, ".change_reference")
            _builder.set_prop("operation", AAZObjectType)

            operation = _builder.get(".operation")
            if operation is not None:
                operation.set_prop("content", AAZDictType, ".content")
                operation.set_prop("httpMethod", AAZStrType, ".http_method")
                operation.set_prop("uri", AAZStrType, ".uri")

            content = _builder.get(".operation.content")
            if content is not None:
                content.set_elements(AAZAnyType, ".")

            return self.serialize_content(_content_value)

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.change_reference = AAZStrType(
                serialized_name="changeReference",
            )
            _schema_on_200.expiration = AAZStrType()
            _schema_on_200.message = AAZStrType()
            _schema_on_200.result = AAZStrType()
            _schema_on_200.results = AAZListType()
            _schema_on_200.retry_after = AAZStrType(
                serialized_name="retryAfter",
            )
            _schema_on_200.token = AAZStrType()
            _schema_on_200.token_id = AAZStrType(
                serialized_name="tokenId",
            )

            results = cls._schema_on_200.results
            results.Element = AAZObjectType()

            _element = cls._schema_on_200.results.Element
            _element.claims = AAZDictType()
            _element.expiration = AAZStrType()
            _element.message = AAZStrType()
            _element.policy_info = AAZObjectType(
                serialized_name="policyInfo",
            )
            _element.result = AAZStrType()
            _element.retry_after = AAZStrType(
                serialized_name="retryAfter",
            )

            claims = cls._schema_on_200.results.Element.claims
            claims.Element = AAZAnyType()

            policy_info = cls._schema_on_200.results.Element.policy_info
            policy_info.ancestors = AAZStrType()
            policy_info.compliance_reason_code = AAZStrType(
                serialized_name="complianceReasonCode",
            )
            policy_info.policy_assignment_display_name = AAZStrType(
                serialized_name="policyAssignmentDisplayName",
            )
            policy_info.policy_assignment_id = AAZStrType(
                serialized_name="policyAssignmentId",
            )
            policy_info.policy_assignment_name = AAZStrType(
                serialized_name="policyAssignmentName",
            )
            policy_info.policy_assignment_scope = AAZStrType(
                serialized_name="policyAssignmentScope",
            )
            policy_info.policy_assignment_version = AAZStrType(
                serialized_name="policyAssignmentVersion",
            )
            policy_info.policy_definition_display_name = AAZStrType(
                serialized_name="policyDefinitionDisplayName",
            )
            policy_info.policy_definition_effect = AAZStrType(
                serialized_name="policyDefinitionEffect",
            )
            policy_info.policy_definition_group_names = AAZListType(
                serialized_name="policyDefinitionGroupNames",
            )
            policy_info.policy_definition_id = AAZStrType(
                serialized_name="policyDefinitionId",
            )
            policy_info.policy_definition_name = AAZStrType(
                serialized_name="policyDefinitionName",
            )
            policy_info.policy_definition_reference_id = AAZStrType(
                serialized_name="policyDefinitionReferenceId",
            )
            policy_info.policy_definition_version = AAZStrType(
                serialized_name="policyDefinitionVersion",
            )
            policy_info.policy_exemption_ids = AAZListType(
                serialized_name="policyExemptionIds",
            )
            policy_info.policy_set_definition_category = AAZStrType(
                serialized_name="policySetDefinitionCategory",
            )
            policy_info.policy_set_definition_display_name = AAZStrType(
                serialized_name="policySetDefinitionDisplayName",
            )
            policy_info.policy_set_definition_id = AAZStrType(
                serialized_name="policySetDefinitionId",
            )
            policy_info.policy_set_definition_name = AAZStrType(
                serialized_name="policySetDefinitionName",
            )
            policy_info.policy_set_definition_version = AAZStrType(
                serialized_name="policySetDefinitionVersion",
            )
            policy_info.resource_location = AAZStrType(
                serialized_name="resourceLocation",
            )

            policy_definition_group_names = cls._schema_on_200.results.Element.policy_info.policy_definition_group_names
            policy_definition_group_names.Element = AAZStrType()

            policy_exemption_ids = cls._schema_on_200.results.Element.policy_info.policy_exemption_ids
            policy_exemption_ids.Element = AAZStrType()

            return cls._schema_on_200


class _AcquireTokenHelper:
    """Helper class for AcquireToken"""


__all__ = ["AcquireToken"]
